version: '3.8'
# [DevOps Standards Optimization] Explicitly define project name (Project Name)
# This name determines the outermost folded group name in Docker Desktop (the building name)
name: hkbu_7940_campusbot_project

# Services are the various services we want to start
services:
  telegram-bot:
    # Tell Docker Compose to use the Dockerfile in the current directory to build the image
    build: .
    # Give this container a nice name
    container_name: hkbu_7940_campusbot_prod
    # Automatically restart it if the container crashes or the computer restarts (ensuring high availability)
    restart: unless-stopped
    # [Security Core] Here we inject the local .env file into the container's environment variables
    # This way, passwords do not appear in the code repository or the image
    env_file:
      - .env
