version: '3.8'
# 【DevOps 规范优化】显式定义项目名称 (Project Name)
# 这个名字决定了 Docker Desktop 最外层折叠组的名字（大楼名字）
name: hkbu_7940_campusbot_project

# Services 就是我们要启动的各种服务
services:
  telegram-bot:
    # 告诉 Docker Compose，使用当前目录的 Dockerfile 来构建镜像
    build: .
    # 给这个容器起个好听的名字
    container_name: hkbu_7940_campusbot_prod
    # 容器崩溃或电脑重启时，自动重启它（保障高可用性）
    restart: unless-stopped
    # 【安全核心】这里我们将本地的 .env 文件注入到容器内部的环境变量中
    # 这样，密码就不会出现在代码仓库或镜像里了
    env_file:
      - .env